### ISSUE TITLE
Travis CI support

### ISSUE THREAD

**Issue by 9il** [kyllingstad/zmqd#12]
Travis CI fails when linking https://travis-ci.org/9il/zmqd .

**Comment by kyllingstad** [comment]
I think that is because Travis does not provide the ZeroMQ libraries. At least, that was the case the last time I tried to set up a Travis job for zmqd. There's not much I can do about that, unfortunately.

**Comment by 9il** [comment]
ZeroMQ in Travis's whitelist and it _is provided_. The error accuse when linking with libzmq, it does not contains some name, but it is represented!

**Comment by kyllingstad** [comment]
Which ZMQ version does Travis provide?

**Comment by 9il** [comment]
4.0.4

**Comment by 9il** [comment]
http://packages.ubuntu.com/trusty/libzmq3-dev

**Comment by 9il** [comment]
Other ZMQ binding with Travis support https://travis-ci.org/smira/txZMQ .

**Comment by kyllingstad** [comment]
The 5 missing functions (`zmq_ctx_term`, `zmq_send_const`, `zmq_z85_encode`, `zmq_z85_decode` and `zmq_curve_keypair`) were all introduced in ZeroMQ 4.0.0, so if Travis uses a newer version, they should be there. According to [this page](http://docs.travis-ci.com/user/installing-dependencies/) Travis uses Ubuntu 12.04, which only has ZeroMQ 2.1, but this may of course be outdated. Is there any way to verify that the libraries are in fact v4.x?

txZMQ does not seem to use any ZeroMQ 4.0 features, which is probably why it works with Travis.

**Comment by 9il** [comment]
This way
```D
language: d

before_script:
  - wget http://download.zeromq.org/zeromq-4.0.7.tar.gz -O /tmp/zeromq-4.0.7.tar.gz
  - tar -xvf /tmp/zeromq-4.0.7.tar.gz
  - sh -c "cd zeromq-4.0.7 && ./configure && make -j 8 && sudo make install"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/:/usr/lib
```
This works with 0.5, but assert errors with alpha (looks like alpha bug).

**Comment by 9il** [comment]
You can check error with https://travis-ci.org/9il/zmqd

**Comment by kyllingstad** [comment]
Ok, thank you! I will look into it as soon as possible.

**Comment by kyllingstad** [comment]
Ok, I think I know what the problem is.

The "invalid argument" error comes from `zmq_getsockopt()` when it is called with `option_name=ZMQ_CURVE_SERVER` by `Socket.curveServer()`. Looking at [the ZeroMQ source code](https://github.com/zeromq/zeromq4-x/blob/master/src/options.cpp#L578), this is probably because ZeroMQ was compiled without [libsodium](https://libsodium.org) (encryption) support. ZMQD simply assumes that encryption is available, because that's how the standard distribution is compiled.

A possible solution is to add `version` blocks to ZMQD that disable encryption support, so it is possible to use it without libsodium-enabled ZMQ libraries. In general, I'm reluctant to adding `version` blocks, though, because each combination of `version` specifiers is effectively a separate library that needs to be tested. I will do some research into how common it is to use ZMQ without libsodium before I decide.

**Comment by kyllingstad** [comment]
ZMQD may now be compiled with `-version=WithoutLibsodium`; see b5fc2476ec6c9acf0debc0519e2754537fb3b342.
