### ISSUE TITLE
Getting Lots of 'undefined symbols' When DUB TESTing ZMQD

### ISSUE THREAD

**Issue by chuckmoore55** [kyllingstad/zmqd#18]
Hi and Thanks for Putting This Together,
Here's (a snippet of) what I just got:
==> dub fetch zmqd
Fetching zmqd 1.0.0...
Placing zmqd 1.0.0 to C:\Users\chais140\AppData\Roaming\dub\packages\...
Please note that you need to use `dub run <pkgname>` or add it to dependencies of your package to actually use/run it. dub does not do actual installation of packages outside of its own ecosystem.
==> dub run zmqd
Building package zmqd in C:\Users\chais140\AppData\Roaming\dub\packages\zmqd-1.0.0\
Performing "debug" build using dmd for x86.
zmqd 1.0.0: target for configuration "library" is up to date.
Target is a library. Skipping execution.
==> dub test zmqd
Building package zmqd in C:\Users\chais140\AppData\Roaming\dub\packages\zmqd-1.0.0\
Generating test runner configuration '__test__library__' for 'library' (library).
Performing "unittest" build using dmd for x86.
zeromq 4.1.2: target for configuration "library" is up to date.
zmqd 1.0.0: building configuration "__test__library__"...
..\..\..\..\..\AppData\Roaming\dub\packages\zmqd-1.0.0\src\zmqd.d(94,12): Deprecation: module std.c.windows.winsock is deprecated - Import core.sys.windows.winsock2 instead
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
zmq.lib
 Warning 2: File Not Found zmq.lib
..\..\..\..\..\AppData\Roaming\dub\packages\zmqd-1.0.0\.dub\build\__test__library__-unittest-windows-x86-dmd_2070-381368EB939E17D24990AFE76425B02C\__test__library__.obj(__test__library__)
 Error 42: Symbol Undefined _zmq_getsockopt
..\..\..\..\..\AppData\Roaming\dub\packages\zmqd-1.0.0\.dub\build\__test__library__-unittest-windows-x86-dmd_2070-381368EB939E17D24990AFE76425B02C\__test__library__.obj(__test__library__)
 Error 42: Symbol Undefined _zmq_poll
.... ( and lots of other 'symbol undefined' messages ) ...

Am I missing something, or doing something in the wrong order ?
Chuck

**Comment by kyllingstad** [comment]
Note the line in there that says: `Warning 2: File Not Found zmq.lib`

Apparently, the linker can't find the ZeroMQ library file, which is why you're getting a lot of undefined references.

**Disclaimer:** Before I say anything more, let me warn you that I have not tested ZMQD on Windows myself. I do have some experience with ZeroMQ on Windows, but only with C++. That said, I do believe it should work, but it may require some effort on your part.

Things you can check:

  1. That you have in fact installed ZeroMQ
  2. That it's located somewhere where DMD can find it. Last I checked (which, admittedly, was a while ago) there was no way to do this via Dub. You probably have to edit the DMD configuration file, or maybe there is an environment variable you can set.
  3. That the library name is correct. The standard ZeroMQ installation package uses a different naming convention on Windows. Rather than simply `zmq.lib`, the library may be named something along the lines of `libzmq-v120-mt-4_1_0.lib`, where `v120` means it's compiled for Visual Studio 12 (2013), `4_1_0` means it's ZeroMQ v4.1.0, etc. Again, I don't know of any way to detect this using Dub, so you probably have to edit the ZMQD Dub file manually.

I'm sorry that it's such a hassle, but these are limitations/quirks in the build tools and the OS that I don't really have a good way to work around. The easiest solution may simply be to locate the correct ZeroMQ file manually, rename it to `zmq.lib`, and place it in the directory from which you run the D compiler...

**Comment by chuckmoore55** [comment]
Morning,

Thanks very much for the assistance. 
1) It turns out that when using VisualD, the safest/guaranteed-way-to-make-things-visible-to-DMD is to load everything (as in anything one imports-from, or references with the linker) into the 'solution' using the Add > Existing Items option found by right-clicking the solution's name in  'Solution Explorer'. Fiddling with environment variables, or the 'sci.ini' file, or putting things in the same directory, only gets confusing messages. 
2) So what I ended up having as additional items alongside 'main.d' : libsodium.lib, libzmq-v110_xp_mt-4_0_4.lib, zeromq.lib, zmqd.d, and zmqd.lib. There is certainly some duplication of functions in this list, but VisualD wasn't happy until I had all of these items added.
3) Finally, I also had to (download and) use the 'coffimpllib' utility on ALL the lib files. 

I'll post these results onto my question on the dlang website, in the event others might find the information useful.

Again, thanks very much for the quick response and encouragement,
Chuck

**Comment by kyllingstad** [comment]
And thanks to you for posting the solution here and in the forum! If ZMQD sees more use in the Windows D community in the future, I suppose this might become a FAQ.

Don't hesitate to let me know if you run into other problems. As I said, the library hasn't been tested much on Windows yet, so I'm quite interested to hear how it works.

**Comment by kyllingstad** [comment]
BTW, I noticed that you use ZeroMQ v4.0. If you haven't done so already, please read the section titled "A word of caution about the C library bindings" in the ZMQD README file. ZeroMQ v4.0, v4.1.0 and v4.1.1 are all binary incompatible with each other, so you need to make sure you use the correct version of the Deimos bindings. Otherwise, your program *will* crash.

**Comment by chuckmoore55** [comment]
Hi,

Thanks for the pointer. 

I did read that section, and had thought I'd gotten everything in-sync. However, I think I might not have reached the correct conclusion(s):
1) The ZMQ website (using the link you've provided for ' ') shows "Current Stable Release 4.1.4", but if one does go to the Windows Installer for that option (4.1.4), the actual files downloaded all have 4_0_4 in their names. I figured (that) this was just part of the overall naming convention. 
2) The 'C Library bindings' link pointing to 'D-Programming-Deimos/ZeroMQ' references 'ZMQ 4.1.2', which again I had assumed to be correct. (Also, I didn't see any references at that site (Deimos/ZeroMQ) to earlier versions.
My apologies on the confusion on my part. I'll check, on Monday, into building ZMQ V4.1.2 from scratch (although I'd rather not do that unless I have to). 

Thanks again for the quick response,
Chuck

**Comment by kyllingstad** [comment]
1. Yeah, I know. Their download link is wrong, and it's actually been like that for a while. In my C++ work with ZeroMQ on Windows I ended up building v4.1 from souce. I seem to remember that as a pretty painless procedure. However, you don't have to do that, because...
  2. The Deimos/ZeroMQ repository contains bindings for multiple ZeroMQ versions. The various Git revisions are tagged with version numbers on the form `vX.Y.Z`. How to get the correct version depends on how you downloaded the bindings:
      - If you use Git, you can check out the `v4.0.4` tag.
      - If you use Dub, you can change the version number in your Dub "selections" file (see Dub documentation).
      - If you want to download it from the Github web interface, you can [browse to the `v4.0.4` tag](https://github.com/D-Programming-Deimos/ZeroMQ/tree/v4.0.4).

**Comment by kyllingstad** [comment]
BTW, you don't have to switch ZMQD versions; it should work with any version of ZeroMQ since 4.0.

**Comment by chuckmoore55** [comment]
Afternoon,

Using your advice on the v4.0.4. tag, I got everything to compile/link using:
1) libzmq-v110_xp-mt-4_0_4
2) import of deimos.zmq.zmq
3) the related syntax of
auto _myContext = zmq_ctx_new();
void* _mySocket = zmq_socket( _myContext , ZMQ_REQ );
zmq_connect( _mySocket, toStringz( _rdrUrl ));
zmq_msg_t _messageToSend;
... (and so on) ...

So, I think that will work good enough. 

As an experiment, though, I commented out all of the (working/compiling/linking) ZeroMQ-using lines and tried (please don't laugh):
1)  libzmq-v110_xp-mt-4_0_4
2) import of zmqd
3) the syntax of 
auto _mySocket = Socket( SocketType.req );
_mySocket.connect( _rdrUrl );
_mySocket.send( _outMessage );
... (and so on) ...

The (more current syntaxed) solution does indeed compile, however I get two pesky messages:
Error	1	Error: undefined identifier 'zmq_proxy_steerable'	C:\D\zmqd-master\src\zmqd.d	1688	
Error	2	Error: undefined identifier 'zmq_proxy_steerable'	C:\D\zmqd-master\src\zmqd.d	1696	

So, I'm putting that down to my having a back-level 'libzmq'. (I did try to to compile, on Windows, a newer libzmq, but ran into 'invalid or corrupt file' errors after 'coffimplib-ing' the libsodium lib.)
Chuck

**Comment by chuckmoore55** [comment]
Lars,

Got the most recent version (4.1.5) of zmq to compile/link: 
1) downloaded libsodium binaries, renamed them to the name needed by zmq's solution, twiddled with the 'additional library directories' to look at them (needed even though the renamed-name was specified elsewhere), and it (libzmq) built! Nothing else built in that solution, but c`est la zmq. 
Then, in my originally-desired solution:
1) Added (newly built) libzmq to originally-desired solution
2) Commented out 'zmq_proxy_steerable' lines within zmqd.d (not the best way to go about it, but I'm not going to be using 'zmq_proxy_steerable' that I know of)

So, the originally-desired-solution/impetus for all this running-around may still crash, but I've got something. And if needed, I could always drop back to the 4.0.4 way-of-doing-things.

Thanks again for your assistance and encouragement,
Chuck

**Comment by kyllingstad** [comment]
Looks like you uncovered a bug in zmqd. The `zmq_proxy_steerable()` function was added in ZeroMQ v4.0.5, yet zmqd tries to use it even if the bindings are of an earlier version. I'll get that fixed.

When using ZeroMQ v4.1.5, it is probably a good idea to use 4.1 bindings too. Deimos/ZeroMQ is currently at v4.1.2, but I'd be very surprised if that version doesn't work with 4.1.5. Anyway, I'll make sure that the Deimos bindings also get an update in the near future.

**Comment by chuckmoore55** [comment]
Lars,

To let you know: got the sucker to talk (to itself) on Windows as 4.1.5.
Program arguments:
 ... option: START
 ... port: 5555
 ... name: MyReader

Received Hello
Received Hello
Received Hello
Received Hello
Received Hello
Received Hello
Received Hello
Received Hello
Received Hello
Received Hello

----------------- client console ---------------
 ... option: QUERY
 ... port: 5555
 ... name: MyReader

Connecting to hello world server├óΓé¼┬ª
Sending Hello 0├óΓé¼┬ª
Received World 0
Sending Hello 1├óΓé¼┬ª
Received World 1
Sending Hello 2├óΓé¼┬ª
Received World 2
Sending Hello 3├óΓé¼┬ª
Received World 3
Sending Hello 4├óΓé¼┬ª
Received World 4
Sending Hello 5├óΓé¼┬ª
Received World 5
Sending Hello 6├óΓé¼┬ª
Received World 6
Sending Hello 7├óΓé¼┬ª
Received World 7
Sending Hello 8├óΓé¼┬ª
Received World 8
Sending Hello 9├óΓé¼┬ª
Received World 9
MyReader : Ending

Thanks again,
Chuck
